### ISSUE TITLE
Navigation Drawer Geliştirmesi

### ISSUE THREAD

**Issue by msayan** [mustafakuloglu/file-manager#4]

**Comment by abdulmelikkesikbas** [comment]
Navigation Drawer itemleri güncellendi.İconlar eklenecek

**Comment by abdulmelikkesikbas** [comment]
İconlar eklendi.

**Comment by abdulmelikkesikbas** [comment]
Geliştirme tamamlandı

**Comment by msayan** [comment]
menü butonu düzenlenecek.

**Comment by mustafakuloglu** [comment]
İşlevsel olarak navigation drawer tamamlandı belki görsel düzenlemeler yapılabilir.

**Comment by abdulmelikkesikbas** [comment]
Görev tamamlandı
